short_fields:
  # Default is long format: These are the exceptions.
  - /deployment/basic/name
  - /deployment/basic/data_product_type
  - /deployment/basic/data_product_region
  - /deployment/basic/data_product_sector
  - /deployment/basic/publication_date
  - /deployment/dp_variant/variant_name
  - /deployment/privacy_loss/privacy_unit
  - /deployment/privacy_loss/privacy_parameters/epsilon
  - /deployment/privacy_loss/privacy_parameters/delta
  - /deployment/privacy_loss/privacy_parameters/rho
  - /deployment/deployment_model/model_name
  - /deployment/deployment_model/release_type
  - /deployment/deployment_model/access_type
  - /deployment/deployment_model/data_source_type
extra_columns:
  # Keys are the display names of columns;
  # Values are the path to the value to show.
  "Model": /deployment/deployment_model/model_name
tile_names:
  # These tiles in the table need shorter names.
  preprocessing_and_hyperparameter_tuning: Pre Processing
