name: Daily
on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  daily:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check deployments (including URLs)
        run: scripts/check.py

      - name: Check schema urls
        run: scripts/check.py --yaml_path schemas/deployments-schema.yaml --only check_urls
